version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
  build:
    commands:
      - echo during build time
  post_build:
    commands:
      - echo build Docker image complete `date`